backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: img

collections:
- name: "blog"
  label: "Blog"
  folder: "src/pages/blog/posts"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  editor:
    preview: false

- name: "events"
  label: "Events"
  folder: "src/pages/tour-calendar/events"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  editor:
    preview: false

- name: "tours"
  label: "Tours"
  folder: "src/pages/tours"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-page"}
    - {label: "Featured?", name: "featured", widget: "boolean", default: false}
    - label: "Destination"
      name: "destination"
      widget: "relation"
      collection: "destinations"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - label: "Activity"
      name: "activity"
      widget: "relation"
      collection: "activities"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Duration", name: "duration", widget: "string"}
    - {label: "Price", name: "price", widget: "string"}
    - label: "Image Thumbnail"
      name: imagethumbnail
      widget: object
      fields: 
        - {label: Image, name: image, widget: image, hint: "size 375 x 375"}
        - {label: Alt, name: alt, widget: string}    
  editor:
    preview: false
           
- name: "pages"
  label: "Pages"
  files:
    - file: "src/pages/index.md"
      label: "Home Page"
      name: "homepage"
      fields:
        - {label: "Template Key", name: templateKey, widget: hidden, default: "home-page"}
        - label: Slider
          name: slider
          widget: list
          fields: 
            - label: "Slide"
              name: slide
              widget: object
              fields: 
                - {label: Heading, name: heading, widget: "markdown"}
                - {label: Subheading, name: subheading, widget: "markdown"}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image, hint: "size 1600 x 987"}
                    - {label: Alt, name: alt, widget: string}
        - label: "About Area"
          name: aboutarea
          widget: object
          fields: 
            - {label: Heading, name: heading, widget: "markdown"}
            - label: "Image"
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image, hint: "size 786 x 426"}
                - {label: Alt, name: alt, widget: string}       
            - {label: Blur, name: blur, widget: text}     
        - label: "Tours Area"
          name: toursarea
          widget: object
          fields:
            - {label: Heading, name: heading, widget: "markdown"}
            - {label: Introduction, name: introduction, widget: text}
            - label: "Block"
              name: block
              widget: list
              fields:
                - {label: Heading, name: heading, widget: "markdown"}
                - label: Tours
                  name: tours 
                  widget: list
                  fields:
                    - label: "Tour"
                      name: "tour"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
        - label: "Blog Area"
          name: blogarea
          widget: object
          fields: 
            - {label: Switch, name: switch, widget: boolean}
            - {label: Heading, name: heading, widget: "markdown"}
    - file: "src/pages/about/index.md"
      label: "About Page"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  editor:
    preview: false

- name: "tourmenu"
  label: "Tour Menu"
  file: "src/general/tourMenu.md"
  widget: list
  fields:
    - {label: Heading, name: heading, widget: string, default: ""}
    - label: "Image"
      name: image
      widget: object
      fields: 
        - {label: Image, name: image, widget: image}
        - {label: Alt, name: alt, widget: string}
        - label: "Tours"
          name: "tours"
          widget: list
          fields:
            - label: "Tour"
              name: "tour"
              widget: "relation"
              collection: "tours"
              searchFields: ["title"] 
              valueField: "title"
              displayFields: ["title"]
  editor:
    preview: false

- name: "general"
  label: "General"
  files:
    - file: "src/general/contact.md"
      label: "Contact Details"
      name: "contact"
      fields:
        - label: "Contact Details"
          name: contact-details
          widget: object
          fields:
            - {label: Email Address, name: email, widget: string}
            - {label: Phone Number, name: phone, widget: string}

    - file: "src/general/footer.md"
      label: "Footer"
      name: "footer"
      fields:
        - label: "Background Image"
          name: image
          widget: object
          fields: 
            - {label: Image, name: image, widget: image, hint: "size 1600 x 553"}
            - {label: Alt, name: alt, widget: string}
  folders:
    - name: "destinations"
      label: "Destinations"
      folder: "src/general/destinations"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}

    - name: "activities"
      label: "Activities"
      folder: "src/general/activities"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
  editor:
    preview: false
