backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
- name: events
  label: "Events"
  folder: "src/general/events"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
  - label: "Tour"
    name: "title"
    widget: "relation"
    collection: "tours"
    searchFields: ["title"] 
    valueField: "title"
    displayFields: ["title"]
  - {label: "Date", name: "date", widget: "datetime"}
  editor:
    preview: false

- name: "blog"
  label: "Blog"
  folder: "src/pages/blog/posts"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  editor:
    preview: false

- name: "tours"
  label: "Tours"
  folder: "src/pages/tours"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-page"}
    - {label: "Featured?", name: "featured", widget: "boolean", default: false}
    - {label: "Title", name: "title", widget: "string"}
    - label: "Destination"
      name: "destination"
      widget: "relation"
      collection: "destinations"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - label: "Activity"
      name: "activity"
      widget: "relation"
      collection: "activities"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - {label: "Duration", name: "duration", widget: "string"}
    - {label: "Price", name: "price", widget: "string"}
    - {label: "Short Description", name: "shortdescription", widget: "text"}
    - {label: "Long Description", name: "body", widget: "markdown"}
    - {label: "Banner Blurb", name: "bannerblurb", widget: "text"}
    - label: "Thumbnail Image"
      name: imagethumbnail
      widget: object
      required: false
      fields: 
        - {label: Image, name: image, widget: image, hint: "size 375 x 375"}
        - {label: Alt, name: alt, widget: text,  required: false}  
    - label: "Banner Image"
      name: imagebanner
      widget: object
      required: false
      fields: 
        - {label: Image, name: image, widget: image, hint: "size 1600 x 596"}
        - {label: Alt, name: alt, widget: text,  required: false}
    - label: "Photo Gallery"
      name: photoGallery
      widget: object
      required: false
      fields:
        - label: Photo
          name: photo
          widget: list
          fields:
            - {label: Image, name: image, widget: image, hint: "size 800 x 600"}
            - {label: Alt, name: alt, widget: text,  required: false}
            - {label: Caption, name: caption, widget: text,  required: false}

  editor:
    preview: false
           
- name: "pages"
  label: "Pages"
  files:
    - file: "src/pages/index.md"
      label: "Home Page"
      name: "homepage"
      fields:
        - {label: "Template Key", name: templateKey, widget: hidden, default: "home-page"}
        - label: Slider
          name: slider
          widget: list
          fields: 
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Subheading 1, name: subheading1, widget: string}
            - {label: Subheading 2, name: subheading2, widget: string}
            - label: Image
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image, hint: "size 1600 x 987"}
                - {label: Alt, name: alt, widget: text,  required: false}
        - label: "About Area"
          name: aboutarea
          widget: object
          fields: 
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Blurb, name: blurb, widget: text}     
            - label: "Image"
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image, hint: "size 786 x 426"}
                - {label: Alt, name: alt, widget: text,  required: false}       
        - label: "Tours Area"
          name: toursarea
          widget: object
          fields:
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Blurb, name: introduction, widget: text}
            - label: "Section"
              name: section
              widget: list
              fields:
                - {label: Heading 1, name: heading1, widget: string}
                - {label: Heading 2, name: heading2, widget: string}
                - label: Tours
                  name: tours 
                  widget: list
                  fields:
                    - label: "Tour"
                      name: "tour"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
        - label: "Blog Area"
          name: blogarea
          widget: object
          fields: 
            - {label: Switch, name: switch, widget: boolean}
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Blurb, name: blurb, widget: text}     
    - file: "src/pages/about/index.md"
      label: "About Page"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - label : Banner
          name: banner
          widget: object
          fields:
            - {label: Blurb, name: blurb, widget: text} 
            - label: "Banner Image"
              name: imagebanner
              widget: object
              fields: 
                - {label: Image, name: image, widget: image, hint: "size 1600 x 596"}
                - {label: Alt, name: alt, widget: text,  required: false}    
        - label: "About Area"
          name: aboutarea
          widget: object
          fields: 
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - label: "Image"
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image, hint: "size 785 x 647"}
                - {label: Alt, name: alt, widget: text,  required: false}       
            - {label: Text, name: text, widget: text}     
        - label: Destinations Area
          name: destinationsarea
          widget: object
          fields:
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Blurb, name: introduction, widget: text}
            - label: "Destination"
              name: destination
              widget: list
              fields:
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image, hint: "size 540 x 300"}
                    - {label: Alt, name: alt, widget: text,  required: false}                    
                - {label: Heading 1, name: heading1, widget: string}
                - {label: Heading 2, name: heading2, widget: string}
                - label: Content 
                  name: content
                  widget: object
                  fields:
                    - label: Paragraph
                      name: paragraph
                      widget: list
                      fields:
                        - {label: Text, name: text, widget: text}
        - label: Partners Area
          name: partnersarea  
          widget: object
          fields:
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - {label: Blurb, name: introduction, widget: text}
            - label: "Partner"
              name: partner
              widget: list
              fields:
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image, hint: "size 540 x 300"}
                    - {label: Alt, name: alt, widget: text,  required: false}                    
                - {label: Heading 1, name: heading1, widget: string}
                - {label: Heading 2, name: heading2, widget: string}
                - label: Content 
                  name: content
                  widget: object
                  fields:
                    - label: Paragraph
                      name: paragraph
                      widget: list
                      fields:
                        - {label: Text, name: text, widget: text}
    - file: "src/pages/contact/index.md"
      label: "Contact Page"
      name: contact
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
        - {label: Blurb, name: blurb, widget: text} 
        - label: "Banner Image"
          name: imagebanner
          widget: object
          fields: 
            - {label: Image, name: image, widget: image, hint: "size 1600 x 596"}
            - {label: Alt, name: alt, widget: text,  required: false}    
    - file: "src/pages/tour-calendar/index.md"
      label: "Tour Calendar Page"
      name: tourcalendar
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-calendar-page"}
        - {label: Blurb, name: blurb, widget: text} 
        - label: "Banner Image"
          name: imagebanner
          widget: object
          fields: 
            - {label: Image, name: image, widget: image, hint: "size 1600 x 596"}
            - {label: Alt, name: alt, widget: text,  required: false}    
    - file: "src/pages/blog/index.md"
      label: "Blog Page"
      name: bloglist
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-list"}
        - {label: Blurb, name: blurb, widget: text} 
        - label: "Banner Image"
          name: imagebanner
          widget: object
          fields: 
            - {label: Image, name: image, widget: image, hint: "size 1600 x 596"}
            - {label: Alt, name: alt, widget: text,  required: false}    
  editor:
    preview: false

- name: "general"
  label: "General"
  files:
    - file: "src/general/tour-menu.md"
      label: "Tour Menu"
      name: "tourmenu"
      fields:
        - label: "Section"
          name: section
          widget: list
          fields:
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string}
            - label: "Image"
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image}
                - {label: Alt, name: alt, widget: text,  required: false}
            - label: "Tours"
              name: "tours"
              widget: list
              fields:
                - label: "Tour"
                  name: "tour"
                  widget: "relation"
                  collection: "tours"
                  searchFields: ["title"] 
                  valueField: "title"
                  displayFields: ["title"]
    - file: "src/general/contact.md"
      label: "Contact Details"
      name: "contact"
      fields:
        - label: "Contact Details"
          name: contact-details
          widget: object
          fields:
            - {label: Email Address, name: email, widget: string}
            - {label: Phone Number, name: phone, widget: string}
    - file: "src/general/footer.md"
      label: "Footer"
      name: "footer"
      fields:
        - label: Background Image
          name: image
          widget: object
          fields: 
            - {label: Image, name: image, widget: image, hint: "size 1600 x 553"}
            - {label: Alt, name: alt, widget: text,  required: false}      
        - label: Newsletter Area
          name: newsletterarea
          widget: object
          fields: 
            - {label: Heading 1, name: heading1, widget: string}
            - {label: Heading 2, name: heading2, widget: string} 
            - {label: Blurb, name: blurb, widget: text} 
    - file: "src/general/config.md"
      label: "Configuration"
      name: "config"
      fields:
        - {label: "Blog Switch", name: blogswitch, widget: boolean}
        - {label: "Calendar Switch", name: calendarswitch, widget: boolean}
  editor:
    preview: false

- name: "destinations"
  label: "Destinations"
  folder: "src/general/destinations"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Title", name: "title", widget: "string"}
  editor:
    preview: false    

- name: "activities"
  label: "Activities"
  folder: "src/general/activities"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Title", name: "title", widget: "string"}
  editor:
    preview: false 
