backend:
  name: github
  repo: homearanya/wild-coast-walks   # Path to your Github/Gitlab repository
  branch: master    # Branch to update
  base_url: https://myownghuboauthprovider.herokuapp.com # Path to ext auth provider

media_folder: static/img
public_folder: img

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }