backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: img

collections:
- name: "blog"
  label: "Blog"
  folder: "src/pages/blog/posts"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  editor:
    preview: false

- name: "events"
  label: "Events"
  folder: "src/pages/tour-calendar/events"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-page"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  editor:
    preview: false

- name: "tours"
  label: "Tours"
  folder: "src/pages/tours"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-page"}
    - {label: "Featured?", name: "featured", widget: "boolean", default: false}
    - label: "Destination"
      name: "destination"
      widget: "relation"
      collection: "destinations"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - label: "Activity"
      name: "activity"
      widget: "relation"
      collection: "activities"
      searchFields: ["title"] 
      valueField: "title"
      displayFields: ["title"]
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Duration", name: "duration", widget: "string"}
    - {label: "Price", name: "price", widget: "string"}
    - label: "Image Thumbnail"
      name: image
      widget: object
      fields: 
        - {label: Image, name: image, widget: image, hint: "size 375 x 375"}
        - {label: Alt, name: alt, widget: string}    
  editor:
    preview: false
           
- name: "pages"
  label: "Pages"
  files:
    - file: "src/pages/index.md"
      label: "Home Page"
      name: "homepage"
      fields:
        - {label: "Template Key", name: templateKey, widget: hidden, default: "home-page"}
        - label: Slider
          name: slider
          widget: object
          fields: 
            - label: "Slide 1"
              name: slide1
              widget: object
              fields: 
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - {label: Subheading 1, name: subheading1, widget: string, default: ""}
                - {label: Subheading 2, name: subheading2, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
            - label: "Slide 2"
              name: slide2
              widget: object
              fields: 
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - {label: Subheading 1, name: subheading1, widget: string, default: ""}
                - {label: Subheading 2, name: subheading2, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
        - label: "About Area"
          name: aboutarea
          widget: object
          fields: 
            - {label: Heading 1, name: heading1, widget: string, default: ""}
            - {label: Heading 2, name: heading2, widget: string, default: ""}
            - label: "Image"
              name: image
              widget: object
              fields: 
                - {label: Image, name: image, widget: image}
                - {label: Alt, name: alt, widget: string}       
            - {label: Blur, name: blur, widget: text}     
        - label: "Tours Area"
          name: toursarea
          widget: object
          fields:
            - {label: Heading 1, name: heading1, widget: string, default: ""}
            - {label: Heading 2, name: heading2, widget: string, default: ""}
            - {label: Introduction, name: introduction, widget: text}
            - label: "Block 1"
              name: block1
              widget: object
              fields:
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - label: Tours
                  name: tours 
                  widget: object
                  fields:
                    - label: "Tour 1"
                      name: "tour1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 2"
                      name: "tour2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 3"
                      name: "tour3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 2"
              name: block2
              widget: object
              fields:
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - label: Tours
                  name: tours 
                  widget: object
                  fields:
                    - label: "Tour 1"
                      name: "tour1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 2"
                      name: "tour2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 3"
                      name: "tour3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 3"
              name: block3
              widget: object
              fields:
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - label: Tours
                  name: tours 
                  widget: object
                  fields:
                    - label: "Tour 1"
                      name: "tour1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 2"
                      name: "tour2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 3"
                      name: "tour3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 4"
              name: block4
              widget: object
              fields:
                - {label: Heading 1, name: heading1, widget: string, default: ""}
                - {label: Heading 2, name: heading2, widget: string, default: ""}
                - label: Tours
                  name: tours 
                  widget: object
                  fields:
                    - label: "Tour 1"
                      name: "tour1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 2"
                      name: "tour2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Tour 3"
                      name: "tour3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
        - label: "Blog Area"
          name: blogarea
          widget: object
          fields: 
            - {label: Switch, name: switch, widget: boolean}
            - {label: Heading 1, name: heading1, widget: string, default: ""}
            - {label: Heading 2, name: heading2, widget: string, default: ""}
    - file: "src/pages/about/index.md"
      label: "About Page"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  editor:
    preview: false

- name: "config"
  label: "Configuration"
  files:
    - file: "src/config/contact.md"
      label: "Contact Details"
      name: "contact"
      fields:
        - label: "Contact Details"
          name: contact-details
          widget: object
          fields:
            - {label: Email Address, name: email, widget: string}
            - {label: Phone Number, name: phone, widget: string}
    - file: "src/config/mainmenu.md"
      label: "Main Menu"
      name: "mainmenu"
      fields:
        - label: "Home Item"
          name: "homeitem"
          widget: object
          fields:
            - {label: Label, name: label, widget: string}
            - {label: Path, name: path, widget: string}
        - label: "Tours Item"
          name: "toursitem"
          widget: object
          fields:
            - {label: Label, name: label, widget: string}
            - label: "Block 1"
              name: block1
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
                - label: "Links"
                  name: "links"
                  widget: object
                  fields:
                    - label: "Link 1"
                      name: "link1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 2"
                      name: "link2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 3"
                      name: "link3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 2"
              name: block2
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
                - label: "Links"
                  name: "links"
                  widget: object
                  fields:
                    - label: "Link 1"
                      name: "link1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 2"
                      name: "link2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 3"
                      name: "link3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 3"
              name: block3
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
                - label: "Links"
                  name: "links"
                  widget: object
                  fields:
                    - label: "Link 1"
                      name: "link1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 2"
                      name: "link2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 3"
                      name: "link3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
            - label: "Block 4"
              name: block4
              widget: object
              fields:
                - {label: Heading, name: heading, widget: string, default: ""}
                - label: "Image"
                  name: image
                  widget: object
                  fields: 
                    - {label: Image, name: image, widget: image}
                    - {label: Alt, name: alt, widget: string}
                - label: "Links"
                  name: "links"
                  widget: object
                  fields:
                    - label: "Link 1"
                      name: "link1"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 2"
                      name: "link2"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
                    - label: "Link 3"
                      name: "link3"
                      widget: "relation"
                      collection: "tours"
                      searchFields: ["title"] 
                      valueField: "title"
                      displayFields: ["title"]
        - label: "Tour Calendar Item"
          name: "tourcalendaritem"
          widget: object
          fields:
            - {label: Label, name: label, widget: string}
            - {label: Path, name: path, widget: string}
        - label: "Blog Item"
          name: "blogitem"
          widget: object
          fields:
            - {label: Switch, name: switch, widget: boolean}
            - {label: Label, name: label, widget: string}
            - {label: Path, name: path, widget: string}
  editor:
    preview: false

- name: "destinations"
  label: "Destinations"
  folder: "src/config/destinations"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Title", name: "title", widget: "string"}
  editor:
    preview: false    

- name: "activities"
  label: "Activities"
  folder: "src/config/activities"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Title", name: "title", widget: "string"}
  editor:
    preview: false    